(ns irc.core-test
  (:require [clojure.test :refer :all]
            [irc.core :refer :all]))

(def messages (seq [
  [ "PASS secretpasswordhere" [:message [:command "PASS"] [:param "secretpasswordhere"]]]
  ["NICK WiZ" [:message [:command "NICK"] [:param "WiZ" ]]]
  [":WiZ NICK Kilroy" [:message [:prefix [:nick "WiZ"]] [:command "NICK"] [:param "Kilroy"]]]
  ["USER guest tolmoon tolsun :Ronnie Reagan" [:message [:command "USER"] [:param "guest"] [:param "tolmoon"] [:param "tolsun"] [:param "Ronnie Reagan"]]]
  [":testnick USER guest tolmoon tolsun :Ronnie Reagan" [:message [:prefix [:nick "testnick"]] [:command "USER"] [:param "guest"] [:param "tolmoon"] [:param "tolsun"] [:param "Ronnie Reagan"]]]
  ["SERVER test.oulu.fi 1 :[tolsun.oulu.fi] Experimental server" [:message [:command "SERVER"] [:param "test.oulu.fi"] [:param "1"] [:param "[tolsun.oulu.fi] Experimental server"]]]
  [":tolsun.oulu.fi SERVER csd.bu.edu 5 :BU Central Server" [:message [:prefix [:servername "tolsun.oulu.fi"]] [:command "SERVER"] [:param "csd.bu.edu"] [:param "5"] [:param "BU Central Server"]]]
  ["OPER foo bar" [:message [:command "OPER"] [:param "foo"] [:param "bar"]]]
  ["QUIT :Gone to have lunch" [:message [:command "QUIT"] [:param "Gone to have lunch"]]]
  ["SQUIT tolsun.oulu.fi :Bad Link ?" [:message [:command "SQUIT"] [:param "tolsun.oulu.fi"] [:param "Bad Link ?"]]]
  [":Trillian SQUIT cm22.eng.umd.edu :Server out of control" [:message [:prefix [:nick "Trillian"]] [:command "SQUIT"] [:param "cm22.eng.umd.edu"] [:param "Server out of control"]]]
  ["JOIN #foobar" [:message [:command "JOIN"] [:param "#foobar"]]]
  ["JOIN &foo fubar" [:message [:command "JOIN"] [:param "&foo"] [:param "fubar"]]]
  ["JOIN #foo,&bar fubar" [:message [:command "JOIN"] [:param "#foo,&bar"] [:param "fubar"]]]
  ["JOIN #foo,#bar fubar,foobar" [:message [:command "JOIN"] [:param "#foo,#bar"] [:param "fubar,foobar"]]]
  ["JOIN #foo,#bar" [:message [:command "JOIN"] [:param "#foo,#bar"]]]
  [":WiZ JOIN #Twilight_zone" [:message [:prefix [:nick "WiZ"]] [:command "JOIN"] [:param "#Twilight_zone"]]]
  ["PART #twilight_zone" [:message [:command "PART"] [:param "#twilight_zone"]]]
  ["PART #oz-ops,&group5" [:message [:command "PART"] [:param "#oz-ops,&group5"]]]
  ["MODE #Finnish +im" [:message [:command "MODE"] [:param "#Finnish"] [:param "+im"]]]
  ["MODE #Finnish +o Kilroy" [:message [:command "MODE"] [:param "#Finnish"] [:param "+o"] [:param "Kilroy"]]]
  ["MODE #Finnish +v WiZ" [:message [:command "MODE"] [:param "#Finnish"] [:param "+v"] [:param "WiZ"]]]
  ["MODE #Fins -s" [:message [:command "MODE"] [:param "#Fins"] [:param "-s"]]]
  ["MODE #42 +k oulu" [:message [:command "MODE"] [:param "#42"] [:param "+k"] [:param "oulu"]]]
  ["MODE #eu-opers +l 10" [:message [:command "MODE"] [:param "#eu-opers"] [:param "+l"] [:param "10"]]]
  ["MODE &oulu +b" [:message [:command "MODE"] [:param "&oulu"] [:param "+b"]]]
  ["MODE &oulu +b *!*@*" [:message [:command "MODE"] [:param "&oulu"] [:param "+b"] [:param "*!*@*"]]]
  ["MODE &oulu +b *!*@*.edu" [:message [:command "MODE"] [:param "&oulu"] [:param "+b"] [:param "*!*@*.edu"]]]
  [":MODE WiZ -w" [:message [:prefix [:nick "MODE"]] [:command "WiZ"] [:param "-w"]]]
  [":Angel MODE Angel +i" [:message [:prefix [:nick "Angel"]] [:command "MODE"] [:param "Angel"] [:param "+i"]]]
  ["MODE WiZ -o" [:message [:command "MODE"] [:param "WiZ"] [:param "-o"]]]
  [":WiZ TOPIC #test :New topic" [:message [:prefix [:nick "WiZ"]] [:command "TOPIC"] [:param "#test"] [:param "New topic"]]]
  ["TOPIC #test :another topic" [:message [:command "TOPIC"] [:param "#test"] [:param "another topic"]]]
  ["TOPIC #test" [:message [:command "TOPIC"] [:param "#test"]]]
  ["NAMES #twilight_zone,#42" [:message [:command "NAMES"] [:param "#twilight_zone,#42"]]]
  ["NAMES" [:message [:command "NAMES"]]]
  ["LIST" [:message [:command "LIST"]]]
  ["LIST #twilight_zone,#42" [:message [:command "LIST"] [:param "#twilight_zone,#42"]]]
  [":Angel INVITE WiZ #Dust" [:message [:prefix [:nick "Angel"]] [:command "INVITE"] [:param "WiZ"] [:param "#Dust"]]]
  ["INVITE WiZ #Twilight_Zone" [:message [:command "INVITE"] [:param "WiZ"] [:param "#Twilight_Zone"]]]
  ["KICK &Melbourne Matthew" [:message [:command "KICK"] [:param "&Melbourne"] [:param "Matthew"]]]
  ["KICK #Finnish John :Speaking English" [:message [:command "KICK"] [:param "#Finnish"] [:param "John"] [:param "Speaking English"]]]
  [":WiZ KICK #Finnish John" [:message [:prefix [:nick "WiZ"]] [:command "KICK"] [:param "#Finnish"] [:param "John"]]]
  [":WiZ VERSION *.se" [:message [:prefix [:nick "WiZ"]] [:command "VERSION"] [:param "*.se"]]]
  ["VERSION tolsun.oulu.fi" [:message [:command "VERSION"] [:param "tolsun.oulu.fi"]]]
  [":WiZ STATS c eff.org" [:message [:prefix [:nick "WiZ"]] [:command "STATS"] [:param "c"] [:param "eff.org"]]]
  ["STATS m" [:message [:command "STATS"] [:param "m"]]]
  ["LINKS *.au" [:message [:command "LINKS"] [:param "*.au"]]]
  [":WiZ LINKS *.bu.edu *.edu" [:message [:prefix [:nick "WiZ"]] [:command "LINKS"] [:param "*.bu.edu"] [:param "*.edu"]]]
  ["TIME tolsun.oulu.fi" [:message [:command "TIME"] [:param "tolsun.oulu.fi"]]]
  ["Angel TIME *.au" [:message [:command "Angel"] [:param "TIME"] [:param "*.au"]]]
  ["CONNECT tolsun.oulu.fi" [:message [:command "CONNECT"] [:param "tolsun.oulu.fi"]]]
  [":WiZ CONNECT eff.org 6667 csd.bu.edu" [:message [:prefix [:nick "WiZ"]] [:command "CONNECT"] [:param "eff.org"] [:param "6667"] [:param "csd.bu.edu"]]]
  ["TRACE *.oulu.fi" [:message [:command "TRACE"] [:param "*.oulu.fi"]]]
  [":WiZ TRACE AngelDust" [:message [:prefix [:nick "WiZ"]] [:command "TRACE"] [:param "AngelDust"]]]
  ["ADMIN tolsun.oulu.fi" [:message [:command "ADMIN"] [:param "tolsun.oulu.fi"]]]
  [":WiZ ADMIN *.edu" [:message [:prefix [:nick "WiZ"]] [:command "ADMIN"] [:param "*.edu"]]]
  ["KILL David (csd.bu.edu <- tolsun.oulu.fi)" [:message [:command "KILL"] [:param "David"] [:param "(csd.bu.edu"] [:param "<-"] [:param "tolsun.oulu.fi)"]]]
]))

(deftest test-message-parsing
  (doseq [[input expected] messages]
    (is (= expected (parse input)))))
